.
.	Assembly file with many errors
.
BAD	START
FIRST	LDDX 	ZERO 	INITIALIZE REGISTERS
	LDA 	ZERO
1LOOP 	ADD 	TABLE,X ADD THE ELEMENTS
	TIX 	COUNT 	ARE WE DONE?
l337@	JLT 	LOOP 	IF NOT, LOOP
TOOLONG	STA 	TOTAL 	STORE THE TOTAL
	RSUB 		AND RETURN
TABLE 	RESW 	20000	FOR THE ARRAY
COUNT 	RESW 	1 	NUMBER OF ELEMENTS
ZERO 	WORD 	0 	CONSTANT
ZERO	BYTE	
TOTAL 	RESW 	1 	PLACE FOR TOTAL
.	END FIRST
